### ISSUE TITLE
UI: Remove zero from transaction amount.

### ISSUE THREAD

**Issue by domielias** [JG0328/paypal-fees-calculator#2]
Hi, I would like to be able to remove the 0 from the transaction amount component.

This is a example of the view when I fill with some digits I can't remove the 0 from the beginning.

![imagen](https://user-images.githubusercontent.com/45079270/163685623-8f4cae4b-39f8-4707-800e-4271b996dc5a.png)

**Comment by JG0328** [comment]
Fixed in the latest commit, now building for Heroku.
